import banner from '../assets/banner2.webp';
export const categories = [
    {
        title: "Education & Training",
        items: [
            {
                id: 1,
                image: banner, // Replace with the correct image path
                title: "Aviation Colleges",
                experts: 2356,
                button: "GET QUOTES",
            },
            {
                id: 2,
                image: banner,
                title: "Air Hostess Training",
                experts: 655,
                button: "GET QUOTES",
            },
            {
                id: 3,
                image: banner,
                title: "Competitive Exam Coaching",
                experts: 3266,
                button: "GET QUOTES",
            },
            {
                id: 4,
                image: banner,
                title: "Cabin Crew Training",
                experts: 410,
                button: "GET QUOTES",
            },
            {
                id: 5,
                image: banner,
                title: "Entrance Exam Coaching",
                experts: 6327,
                button: "GET QUOTES",
            },
        ],
    },
    {
        title: "Home Services",
        items: [
            {
                id: 6,
                image: banner,
                title: "Home Cleaning",
                experts: 1500,
                button: "GET QUOTES",
            },
            {
                id: 7,
                image: banner,
                title: "Appliance Repair",
                experts: 1200,
                button: "GET QUOTES",
            },
            {
                id: 8,
                image: banner,
                title: "Interior Design",
                experts: 2000,
                button: "GET QUOTES",
            },
            {
                id: 9,
                image: banner,
                title: "Packers & Movers",
                experts: 3000,
                button: "GET QUOTES",
            },
        ],
    },
    {
        title: "Business Services",
        items: [
            {
                id: 1,
                image: banner,
                title: "Web Designers",
                experts: 1119,
                button: "GET QUOTES",
            },
            {
                id: 2,
                image: banner,
                title: "Internet Service Providers",
                experts: 349,
                button: "GET QUOTES",
            },
            {
                id: 3,
                image: banner,
                title: "Generator Dealers",
                experts: 1517,
                button: "GET QUOTES",
            },
            {
                id: 4,
                image: banner,
                title: "Security System Dealers",
                experts: 1329,
                button: "GET QUOTES",
            },
            {
                id: 5,
                image: banner,
                title: "Computer Repair & Services",
                experts: 684,
                button: "GET QUOTES",
            },
        ],
    },
    {
        title: "Properties - Buy, Rent And PG",
        items: [
            {
                id: 6,
                image: banner,
                title: "Properties To Buy",
                experts: 36743,
                button: "VIEW MORE",
            },
            {
                id: 7,
                image: banner,
                title: "New Residential Projects",
                experts: 3915,
                button: "VIEW MORE",
            },
            {
                id: 8,
                image: banner,
                title: "Properties To Rent",
                experts: 18720,
                button: "VIEW MORE",
            },
            {
                id: 9,
                image: banner,
                title: "Paying Guest Accommodation",
                experts: 3982,
                button: "VIEW MORE",
            },
            {
                id: 10,
                image: banner,
                title: "Service Apartments To Rent",
                experts: 43,
                button: "VIEW MORE",
            },
        ],
    },
    {
        title: "IT Training",
        items: [
            {
                id: 11,
                image: banner,
                title: "Data Science Course",
                experts: 2704,
                button: "GET QUOTES",
            },
            {
                id: 12,
                image: banner,
                title: "AWS Training In Cloud Computing",
                experts: 2707,
                button: "GET QUOTES",
            },
            {
                id: 13,
                image: banner,
                title: "Hadoop Training",
                experts: 3458,
                button: "GET QUOTES",
            },
            {
                id: 14,
                image: banner,
                title: "Big Data Training",
                experts: 3768,
                button: "GET QUOTES",
            },
            {
                id: 15,
                image: banner,
                title: "Oracle Training",
                experts: 5826,
                button: "GET QUOTES",
            },
        ],
    },
    {
        title: "Health & Wellness",
        items: [
            {
                id: 16,
                image: banner,
                title: "Spa & Relaxation",
                experts: 1250,
                button: "VIEW MORE",
            },
            {
                id: 17,
                image: banner,
                title: "Yoga Instructors",
                experts: 680,
                button: "VIEW MORE",
            },
            {
                id: 18,
                image: banner,
                title: "Personal Trainers",
                experts: 890,
                button: "VIEW MORE",
            },
            {
                id: 19,
                image: banner,
                title: "Beauty & Makeup",
                experts: 4500,
                button: "VIEW MORE",
            },
        ],
    },
];